### ISSUE TITLE
Show images using MediaObject

### ISSUE THREAD

**Issue by amedranogil** [universAAL/ui#142]
_Originally Opened: Hector Galan (2012-05-22 16:10:30_)
_Originally Closed: 2012-05-23 16:32:31_

Trying to display an image using the swing gui handler:
Using mvn:org.universAAL.ui/ui.handler.gui.swing/1.1.0

and the following code:

Form f = Form.newDialog(&quot;My form&quot;, new Resource());
new MediaObject(f.getIOControls(), new Label(&quot;Image&quot;, null), &quot;image/jpeg&quot;, &quot;recipe.jpg&quot;);

Checked with several paths:
&quot;recipe.jpg&quot;, &quot;/recipe.jpg&quot;, &quot;\\recipe.jpg&quot;, &quot;file\\pathToImage/recipe.jpg&quot;

The image recipe.jpg is placed in the following folders:
rundir\confadmin\ui.handler.gui.swing\icons
rundir\confadmin\ui.handler.gui.swing\images
rundir\confadmin\ui.handler.gui.swing\resources

The result I get in the console is (see attached file):
Exception in thread &quot;Thread-14&quot; java.lang.NullPointerException
	at javax.swing.ImageIcon.&lt;init&gt;(Unknown Source)
	at org.universAAL.ui.handler.gui.swing.model.IconFactory.getIcon(IconFactory.java:42)
	at org.universAAL.ui.handler.gui.swing.model.FormControl.MediaObjectModel.update(MediaObjectModel.java:63)
	at org.universAAL.ui.handler.gui.swing.model.Model.getComponent(Model.java:197)
	at org.universAAL.ui.handler.gui.swing.model.FormControl.GroupModel.addComponentTo(GroupModel.java:215)
	at org.universAAL.ui.handler.gui.swing.model.FormControl.GroupModel.updateSimplePanel(GroupModel.java:111)
	at org.universAAL.ui.handler.gui.swing.model.FormControl.GroupModel.update(GroupModel.java:155)
	at org.universAAL.ui.handler.gui.swing.model.Model.getComponent(Model.java:197)
	at org.universAAL.ui.handler.gui.swing.model.FormModel.getIOPanel(FormModel.java:160)
	at org.universAAL.ui.handler.gui.swing.defaultLookAndFeel.FormLAF.getIOPanelScroll(FormLAF.java:72)
	at org.universAAL.ui.handler.gui.swing.defaultLookAndFeel.FormLAF.getFrame(FormLAF.java:160)
	at org.universAAL.ui.handler.gui.swing.formManagement.FrameManager.&lt;init&gt;(FrameManager.java:51)
	at org.universAAL.ui.handler.gui.swing.formManagement.SimpleFormManager.addDialog(SimpleFormManager.java:45)
	at org.universAAL.ui.handler.gui.swing.Handler.handleUICall(Handler.java:77)
	at org.universAAL.middleware.ui.impl.UIStrategy.notifyHandler_handle(UIStrategy.java:800)
	at org.universAAL.middleware.ui.impl.UIStrategy.adaptationParametersChanged(UIStrategy.java:217)
	at org.universAAL.middleware.ui.impl.UIStrategy.handle(UIStrategy.java:568)
	at org.universAAL.middleware.sodapop.BusStrategy$HandlerThread.run(BusStrategy.java:50)

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by amedranogil** [comment]
_Original author: @amedranogil (2012-05-23 16:32:31)_

Fixed in 1.1.2-SNAPSHOT

**Comment by amedranogil** [comment]
issue cloed on 2012-05-23 16:32:31
