### ISSUE TITLE
Concurrent Modification when removing Matching handler parameters

### ISSUE THREAD

**Issue by amedranogil** [universAAL/ui#295]
_Originally Opened: @amedranogil (2013-04-22 17:36:22_)
_Originally Closed: 2013-08-12 12:32:14_

when loging out (removing restriction to match user) the following exception appears:

Exception in thread &quot;AWT-EventQueue-0&quot; java.util.ConcurrentModificationException
	at java.util.Vector$Itr.checkForComodification(Vector.java:1156)
	at java.util.Vector$Itr.next(Vector.java:1133)
	at org.universAAL.middleware.ui.impl.UIStrategy.removeMatchingProfile(UIStrategy.java:1024)
	at org.universAAL.middleware.ui.impl.UIBusImpl.removeMatchingProfile(UIBusImpl.java:220)
	at org.universAAL.middleware.ui.UIHandler.removeMatchingRegParams(UIHandler.java:164)
	at org.universAAL.ui.handler.gui.swing.Handler.unSetCurrentUser(Handler.java:150)
	at org.universAAL.ui.handler.gui.swing.Renderer.logOffCurrentUser(Renderer.java:409)
	at org.universAAL.ui.gui.swing.bluesteelLAF.support.UAALTray$2.actionPerformed(UAALTray.java:78)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by amedranogil** [comment]
issue cloed on 2013-08-12 12:32:14
