### ISSUE TITLE
BluesteelLAF crashesss

### ISSUE THREAD

**Issue by amedranogil** [universAAL/ui#305]
_Originally Opened: @geibsan (2013-06-05 19:20:57_)
_Originally Closed: 2013-09-27 16:18:23_

I am working on Eclipse in Nutritional Advisor service. For the UI I am using the following components/versions each one in a different level and in this order:

* ui.dm/1.3.5-SNAPSHOT
* ui.handler.gui.swing/1.3.3-SNAPSHOT
* ui.handler.gui.swing.bluesteelLAF/1.3.3-SNAPSHOT@notstart

Apart from that I use mw.composite/1.3.3-SNAPSHOT and ont.composite/1.3.3-SNAPSHOT

There is no apparent reason to make it crashes, just suddently appears this error 
and get a grey screen (no main menu or service at all). But I can describe several cases that I followed when I got the error:
- CASE 1-
1. Run the platform and log in.
2. Click in the main menu (NA button). Service is shown.
3. Click in one of the &quot;see recipe&quot; buttons. The recipe is shown in a new screen.
4. Back to the menu screen of the NA by clicking in the back button.
5. Click in Exit button in the NA service.
6. It crashes, grey screen and appears the error in the console output (although it doesn't happen all the times)

- CASE 2 -
1. Run the platform and log in.
2. Click in the main menu (NA button). Service is shown.
3. Click in Exit button in the NA service.
4. Click in Exit button in the main menu.
5. Right-click in tryIcon and Log-on.
6. Type user and pass.
7. Click in Ok button.
8. It crashes, grey screen and appears the error in the console output (although it doesn't happen all the times. If you repeat steps 4-7 in the end usually it crashes, I guess the NA really doesnt influence this)

- CASE 3 - 
1. Run the platform.
2. Wait for 1 minute.
3. Type user and pass.
4. Click in Ok button.
5. It crashes, grey screen and appears the error in the console output (although it doesn't happen all the times)

mw.container.osgi[org.universAAL.ui.handler.gui.swing] : FrameManager-&gt;run(): Starting Rendering
Exception in thread &quot;Thread-152&quot; java.lang.NullPointerException
	at org.universAAL.ui.gui.swing.bluesteelLAF.Init.processPrefs(Init.java:196)
	at org.universAAL.ui.gui.swing.bluesteelLAF.FormLAF.showForm(FormLAF.java:160)
	at org.universAAL.ui.handler.gui.swing.formManagement.FrameManager.run(FrameManager.java:104)
	at java.lang.Thread.run(Thread.java:662)

--

From: _this issue has been automatically imported from our old issue tracker_

**Comment by amedranogil** [comment]
_Original author: @amedranogil (2013-08-12 12:35:47)_

close if it doesn't happen again...

**Comment by amedranogil** [comment]
issue cloed on 2013-09-27 16:18:23
